OpenGenus/cosmos-search

cosmos_search/settings.py
=> Fixed host

README.md
=> Added Readme information

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> Added Issue and PR template

search/templates/cosmos/error/HTTP400.html, search/templates/cosmos/error/HTTP403.html, search/templates/cosmos/error/HTTP404.html, search/templates/cosmos/error/HTTP500.html, search/templates/cosmos/header.html, search/templates/cosmos/notfound.html, search/templates/cosmos/searchresults.html, search/views.py
- Searchresults title will have the query as prefix
- updated custom site titles for each view
=> Dynamic titles

.github/CODE_OF_CONDUCT.md
This pull request adds the basic version of our code of conduct.
=> Code of conduct added

search/templates/cosmos/searchresults.html, search/views.py
=> Added suggestions based on Search query.

README.md
**Checklist**
fixes: #34
This PR introduces changes to the Readme file and adds instruction to set up a virtualenv before running the search engine locally.
=> Add virtualenv command to Readme file

search/templates/cosmos/header.html, search/views.py
**Checklist**
fixes: #21 
Adds functionality to auto fill search bar before hand with random topics from metadata.json to help new users in running project more easily.
Random filled topic:
Random filled topic:
=> prefill search bar

cosmos_search/settings.py
**Checklist**
fixes: #51 
The command ```python manage.py collectstatic``` would collect ```static``` files into static directory.
You can just run the command mentioned above.
- ```/static``` should be in ```.gitignore```
=> static root is defined

cosmos_search/settings.py, search/templates/cosmos/header.html, search/templates/cosmos/searchresults.html, search/views.py
**Checklist**
fixes: #
Some tips for you to write the instructions:
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as migrating databases, etc.
=> Update to master

.travis.yml, cosmos_search/settings.py, cosmos_search/urls.py, manage.py, requirements.txt, search/admin.py, search/models.py, search/templatetags/random_numbers.py, search/tests.py, search/views.py, tox.ini, update/admin.py, update/models.py, update/tests.py, update/views.py
**Checklist**
Fixes: #49 
For better code quality, code linter is necessary.
=> Resolves #49 Add flake8 code linter

search/templates/cosmos/searchresults.html
**Checklist**
fixes: #65 
If user search something up in the engine, and it only has 1 result, it would display: "Showing 1 result for: query"
=> fixes Plurization bug

search/templates/cosmos/header.html, search/templates/cosmos/index.html, search/templates/cosmos/searchresults.html
**Checklist**
fixes: #
1. image distortion and links/search bar alignment
before
after
2. Beautify footer
before
after
=> Fix image distortion, beautify some templates

cosmos_search/settings.py, update/urls.py, update/views.py
**Checklist**
fixes: #
The update-json is not working now, I guess it is either not running or trigger but not with error handling, In second way I found an error because the cosmos path is not the set to root in settings file.
ccbca0e
Before:
After:
Some tips for you to write the instructions:
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as migrating databases, etc.
f83bcc2
@AdiChat If you approved this PR, the webhook needs to be changed also:
=> Fix update json errors.

.travis.yml
**Checklist**
fixes: #85 
``makemigrations``  is responsible for packaging up  model changes into individual migration files - analogous to commits - and ``migrate``  is responsible for applying those to the database.
These commands   play important role to fix ``travis`` build  error.
=> fixes travis build error while working with models

search/templates/cosmos/header.html, search/templatetags/calculator.py
**Checklist**
fixes: #
It restricted the irrelevant search of `empty field` in the search bar. It specifies that an input field must be filled out before submitting the form.
=> input field must be filled before searching

search/static/css/calculator.css, search/templates/cosmos/calculator.html
**Checklist**
fixes: #
+ Fix some error code:
1. Input field is clipped by css.
2. Some css not applied.
+ Improve user experience:
1. Display previous expression when user click clear or type other expression.
2. Change typesetting.
Some tips for you to write the instructions:
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as migrating databases, etc.
before:
after:
1. Implement calculator using javascript instead of python, this change involve multiple benefit, such as decrement computation of server, …
=> Improve user experience

search/views.py
**Checklist**
fixes: #99 
It allows the query with extra spaces. Make search consistent. 
- Search any query with extra spaces.
=> Allow query with trailing, leading and intermediate spaces

search/templates/cosmos/data.html, search/templates/cosmos/searchresults.html, search/urls.py, search/views.py
**Checklist**
fixes: #37 
This works only when DEBUG = True
=>  Display code in search engine instead of redirecting

search/templates/cosmos/calculator.html
**Checklist**
fixes: #
It fixes the broken UI  of calculator for ```Firefox Web Browser```. 
Before
After
=> fixes broken UI calculator

scripts/develop.sh
**Checklist**
fixes: #
1. Reduce time for building developing environment
Some tips for you to write the instructions:
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as migrating databases, etc.
=> Add script for build developing environment

search/templates/cosmos/searchresults.html
**Checklist**
fixes: #37 
It displays the codes in `data.html` page instead of redirecting to GitHub Code links.
=> display code in search engine

README.md
**Checklist**
fixes: #119
To provide instructions for user to run the project without facing any difficulty.
**Demo (optional)**: Not Applicable
- Run the project following the updated set of instructions.
**TODOs (if any)**: No
=> Add instructions for getting youtubeAPI credentials in README

search/templates/cosmos/data.html, search/templates/cosmos/searchresults.html
**Checklist**
fixes: #114 
For each search query we get multiple results, for each results we get the list of solutions. If the user can see the count of files for each it would be better as he/she will get more info.
The PR makes the search queries more informative for the user.
=> count of solutions

search/templates/cosmos/searchresults.html, search/templates/cosmos/youtubeResults.html
**Checklist**
fixes: #
Before (4 snapshots)
1. blank
2. overflow
3. overlapping
4. overlapping
After (3 snapshots)
1.
2.
3.
=> Fix some errors

README.md
**Checklist**
fixes: #132 
This PR helps Anaconda users run the search engine locally by installing the dependencies without any errors.
=> Updated README.md for Anaconda Users

cosmos_search/settings.py, search/templates/cosmos/news.html, search/views.py
**Checklist**
As the title says, this PR adds the pagination feature to the news section. This PR also adds **The Verge** as a news source.
**Demo**:
The Pagination feature
=> Added Pagination to News Section and Other News Sources

README.md
**Checklist**
Added the instructions so that anybody can now contribute to the Human-Curated Lists very easily.
=> Update README for Human-Curated Lists Contribution

search/templates/cosmos/lists_template.html
**Checklist**
Opens all the links in a new tab which helps the user explore the lists with ease.
=> Added new tab functionality

search/templates/cosmos/listsResults.html, search/templates/cosmos/searchresults.html, search/views.py
**Checklist**
This PR shows the human-curated lists in the general search. See Demo for full details.
**Demo**:
Searching for best student discounts in the general search. 
Tab results for Lists.
=> Added lists to general search

search/views.py
**Checklist**
fixes: #144 
This PR fixes the issue related to the loading of json files in windows OS.
=> Updated the method of loading json files for windows users.

human_curated_lists/awesome-competitive-coding.md, lists.json, search/views.py
**Checklist**
In order to expand human curated lists I am adding this awesome competitive programming list that will be beneficial for those who are new to competitive programming.
=> Adding human curated list for competitive programming.
